version: '3.8'

services:
  postgres-producer:
    image: postgres:latest
    container_name: producer-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: producer_db
    volumes:
      - producer-postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  producer-postgres_data:
